name: Corporate-Prophet
favicon: null
layout_spectrum: 0.74669
typography_spectrum: 1
title: 'Corporate-Prophet '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73656854-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#a8cde7'
    - '#fafefe'
    - '#416587'
    - '#6894b7'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.7139450230170041
  rhythmicContrast: 0.9255879039410502
purpose: []
